creator:
- {name: John Blischak, user: blischak.j}
- {name: Jennifer Bryan, user: bryan.j}
- {name: Stephen Crouch, user: crouch.s}
- {name: Matt Davis, user: davis.m}
- {name: Tommy Guy, user: guy.t}
- {name: Michael Hansen, user: hansen.m}
- {name: Katy Huff, user: huff.k}
- {name: Mike Jackson, user: jackson.m}
- {name: Jason Montojo, user: montojo.j}
- {name: Jon Pipitone, user: pipitone.j}
- {name: Anthony Scopatz, user: scopatz.a}
- {name: Will Trimble, user: trimble.will}
- {name: Ethan White, user: white.e}
- {name: Greg Wilson, user: wilson.g}
instructor:
- {name: Joshua Adelman, user: adelman.joshua}
- {name: Aron Ahmadia, user: ahmadia.a}
- {name: Joshua Ainsley, user: ainsley.joshua}
- {name: Russell Alleen-Willlems, user: alleen-willems.russell}
- {name: Carlos Anderson, user: anderson.c}
- {name: Catalina Anghel, user: anghel.catalina}
- {name: Dhavide Aruliah, user: aruliah.d}
- {name: Camille Avestruz, user: avestruz.camille}
- {name: Christie Bahlai, user: bahlai.christie}
- {name: Piotr Banaszkiewicz, user: banaszkiewicz.piotr}
- {name: Pauline Barmby, user: barmby.pauline}
- {name: Diego Barneche, user: barneche.diego}
- {name: Philipp Bayer, user: bayer.p}
- {name: Robert Beagrie, user: beagrie.robert}
- {name: Trevor Bekolay, user: bekolay.trevor}
- {name: Nichole Bennett, user: bennett.n}
- {name: Miguel Bernabeu, user: bernabeu.miguel}
- {name: John Blischak, user: blischak.j}
- {name: Azalee Bostroem, user: bostroem.a}
- {name: Erik Bray, user: bray.e}
- {name: C. Titus Brown, user: brown.ct}
- {name: Jennifer Bryan, user: bryan.j}
- {name: Abigail Cabunoc, user: cabunoc.abigail}
- {name: Rosangela Canino-Koning, user: canino-koning.r}
- {name: Chris Cannam, user: cannam.c}
- {name: Timothy Cerino, user: cerino.t}
- {name: Scott Chamberlain, user: chamberlain.s}
- {name: Cliburn Chan, user: chan.cliburn}
- {name: Daniel Chen, user: chen.daniel}
- {name: Chelsea Chisholm, user: chisholm.chelsea}
- {name: Shreyas Cholia, user: cholia.s}
- {name: Adina Chuang Howe, user: chuang-howe.a}
- {name: Neil Chue Hong, user: chue-hong.n}
- {name: Luis Pedro Coelho, user: coelho.luis}
- {name: John Corless, user: corless.john}
- {name: Stefano Cozzini, user: cozzini.s}
- {name: Stephen Crouch, user: crouch.s}
- {name: Michael Crusoe, user: crusoe.michael}
- {name: Emily Davenport, user: davenport.e}
- {name: Matt Davis, user: davis.m}
- {name: Neal Davis, user: davis.neal}
- {name: Gabriel A. Devenyi, user: devenyi.gabriel}
- {name: Ross Dickson, user: dickson.r}
- {name: Jonah Duckles, user: duckles.jonah}
- {name: Jonathan Dursi, user: dursi.j}
- {name: Justin Ely, user: ely.j}
- {name: Remi Emonet, user: emonet.remi}
- {name: Richard Enbody, user: enbody.r}
- {name: Aaron Erlich, user: erlich.aaron}
- {name: Daniel Falster, user: falster.daniel}
- {name: Xu Fei, user: fei.xu}
- {name: Luis Figueira, user: figueira.l}
- {name: Jordan Fish, user: fish.jordan}
- {name: Rich FitzJohn, user: fitzjohn.rich}
- {name: Robert Flight, user: flight.r}
- {name: Philip Fowler, user: fowler.p}
- {name: Chris Friedline, user: friedline.chris}
- {name: Julian Garcia, user: garcia.julian}
- {name: Aaron Garoutte, user: garoutte.aaron}
- {name: Molly Gibson, user: gibson.molly}
- {name: Ivan Gonzalez, user: gonzalez.ivan}
- {name: Julia Gustavsen, user: gustavsen.j}
- {name: Tommy Guy, user: guy.t}
- {name: Steve Haddock, user: haddock.s}
- {name: Denis Haine, user: haine.denis}
- {name: Jessica Hamrick, user: hamrick.jessica}
- {name: Michael Hansen, user: hansen.m}
- {name: Ted Hart, user: hart.t}
- {name: Joshua Herr, user: herr.joshua}
- {name: James Hetherington, user: hetherington.james}
- {name: Konrad Hinsen, user: hinsen.k}
- {name: Daniel Hocking, user: hocking.daniel}
- {name: Chris Holdgraf, user: holdgraf.c}
- {name: Katy Huff, user: huff.k}
- {name: Luiz Irber, user: irber.luiz}
- {name: Damien Irving, user: irving.d}
- {name: Paul Ivanov, user: ivanov.p}
- {name: Mike Jackson, user: jackson.m}
- {name: Christian Jacobs, user: jacobs.christian}
- {name: David Jones, user: jones.d}
- {name: David Jones, user: jones.dm}
- {name: Jessica Kerr, user: kerr.j}
- {name: W. Trevor King, user: king.wt}
- {name: Ted Kirkpatrick, user: kirkpatrick.ted}
- {name: Justin Kitzes, user: kitzes.j}
- {name: Christina Koch, user: koch.christina}
- {name: Steven Koenig, user: koenig.steven}
- {name: Bernhard Konrad, user: konrad.b}
- {name: Igor Kozlov, user: kozlov.igor}
- {name: Karin Lagesen, user: lagesen.k}
- {name: Ian Langmore, user: langmore.i}
- {name: Jeremiah Lant, user: lant.jeremiah}
- {name: Chris Lasher, user: lasher.c}
- {name: Doug Latornell, user: latornell.d}
- {name: Luke Lee, user: lee.luke}
- {name: JC Leyder, user: leyder.jean-christophe}
- {name: Matthew Lightman, user: lightman.matthew}
- {name: Johnny Lin, user: lin.johnny}
- {name: Elijah Lowe, user: lowe.elijah}
- {name: Yuxi Luo, user: luo.yuxi}
- {name: Cam Macdonell, user: macdonell.cam}
- {name: Steve McGough, user: mcgough.s}
- {name: Sheldon McKay, user: mckay.sheldon}
- {name: Jessica McKellar, user: mckellar.j}
- {name: Emily Jane McTavish, user: mctavish.ej}
- {name: Lauren Michael, user: michael.lauren}
- {name: Simon Michnowicz, user: michnowicz.s}
- {name: Brian Miles, user: miles.brian}
- {name: Bill Mills, user: mills.b}
- {name: Ian Mitchell, user: mitchell.i}
- {name: Ben Morris, user: morris.b}
- {name: Erika Mudrak, user: mudrak.erika}
- {name: Ian Munoz, user: munoz.ian}
- {name: R. David Murray, user: murray.david}
- {name: Lex Nederbragt, user: nederbragt.l}
- {name: Brenna O'Brien, user: obrien.brenna}
- {name: Randy Olson, user: olson.r}
- {name: Jeramia Ory, user: ory.j}
- {name: Geoff Oxberry, user: oxberry.g}
- {name: Aleksandra Pawlik, user: pawlik.a}
- {name: John Pearson, user: pearson.john}
- {name: Jason Pell, user: pell.j}
- {name: David Perez-Suarez, user: perez-suarez.david}
- {name: Fernando Perez, user: perez.f}
- {name: Stefan Pfenninger, user: pfenninger.s}
- {name: Likit Preeyanon, user: preeyanon.likit}
- {name: Francoise Provencher, user: provencher.francoise}
- {name: Karthik Ram, user: ram.k}
- {name: David Rio, user: rio.david}
- {name: Scott Ritchie, user: ritchie.scott}
- {name: James Robinson, user: robinson.james}
- {name: Rosario Robinson, user: robinson.rosario}
- {name: Ariel Rokem, user: rokem.a}
- {name: Billy Rowell, user: rowell.bill}
- {name: Martin Schilling, user: schilling.martin}
- {name: Jorden Schossau, user: schossau.j}
- {name: Anthony Scopatz, user: scopatz.a}
- {name: Michael Selik, user: selik.m}
- {name: Jeffrey Shelton, user: shelton.j}
- {name: Leigh Sheneman, user: sheneman.leigh}
- {name: Raniere Silva, user: silva.raniere}
- {name: Rachel Slaybaugh, user: slaybaugh.rachel}
- {name: Clare Sloggett, user: sloggett.clare}
- {name: Joshua Smith, user: smith.j}
- {name: Mike Smorul, user: smorul.mike}
- {name: Margaret Staton, user: staton.margaret}
- {name: Shoaib Sufi, user: sufi.s}
- {name: Sarah Supp, user: supp.s}
- {name: 'Svaksha ', user: svaksha}
- {name: Gayathri Swaminathan, user: swaminathan.gayathri}
- {name: Bradley Taber-Thomas, user: taber-thomas.bradley}
- {name: Scott Talafuse, user: talafuse.scott}
- {name: Leszek Tarkowski, user: tarkowski.leszek}
- {name: Tracy Teal, user: teal.t}
- {name: Matt Terry, user: terry.m}
- {name: Will Trimble, user: trimble.will}
- {name: Stephen Turner, user: turner.s}
- {name: Vicky Varga, user: varga.vicky}
- {name: Nelle Varoquaux, user: varoquaux.n}
- {name: Bogdan Vera, user: vera.b}
- {name: Alex Viana, user: viana.a}
- {name: Jens von der Linden, user: vonderlinden.jens}
- {name: Ben Waugh, user: waugh.b}
- {name: Ethan White, user: white.e}
- {name: Easton White, user: white.easton}
- {name: Amanda Whitlock, user: whitlock.a}
- {name: Jason Williams, user: williams.jason}
- {name: Lynne Williams, user: williams.l}
- {name: Ryan Williams, user: williams.ryan}
- {name: Greg Wilson, user: wilson.g}
- {name: Kara Woo, user: woo.kara}
- {name: Christopher Woods, user: woods.c}
- {name: April Wright, user: wright.april}
- {name: Thomas Wright, user: wright.thomas}
- {name: Fan Yang, user: yang.fan}
- {name: Naupaka Zimmerman, user: zimmerman.naupaka}
- {name: Andrea Zonca, user: zonca.andrea}
organizer:
- {name: Jorge Aranda, user: aranda.j}
- {name: Casey Bergman, user: bergman.c}
- {name: Bruce Berriman, user: berriman.b}
- {name: Azalee Bostroem, user: bostroem.a}
- {name: Onno Broekmans, user: broekmans.o}
- {name: Amy Brown, user: brown.amy}
- {name: C. Titus Brown, user: brown.ct}
- {name: Alex Chartier, user: chartier.a}
- {name: Shreyas Cholia, user: cholia.s}
- {name: Stefano Cozzini, user: cozzini.s}
- {name: Matt Davis, user: davis.m}
- {name: Ross Dickson, user: dickson.r}
- {name: Jonah Duckles, user: duckles.jonah}
- {name: Dan Ellis, user: ellis.dan}
- {name: Valerie Evans, user: evans.valerie}
- {name: Philip Fowler, user: fowler.p}
- {name: Elise Glen, user: glen.e}
- {name: Carole Goble, user: goble.c}
- {name: Chris Gray, user: gray.c}
- {name: Norman Gray, user: gray.n}
- {name: David Henty, user: henty.d}
- {name: James Hetherington, user: hetherington.james}
- {name: Bill Howe, user: howe.b}
- {name: Katy Huff, user: huff.k}
- {name: Catherine Inglis, user: inglis.catherine}
- {name: Mike Jackson, user: jackson.m}
- {name: Bernhard Konrad, user: konrad.b}
- {name: Nic Kooyers, user: kooyers.n}
- {name: Ian Langmore, user: langmore.i}
- {name: Paul Lu, user: lu.p}
- {name: Andrew Lumsdaine, user: lumsdaine.a}
- {name: Joshua Madin, user: madin.j}
- {name: Avril Manners, user: manners.avril}
- {name: Damian Marchewka, user: marchewka.damian}
- {name: Ian Mitchell, user: mitchell.i}
- {name: Jason Montojo, user: montojo.j}
- {name: Lex Nederbragt, user: nederbragt.l}
- {name: Randy Olson, user: olson.r}
- {name: Chris Paciorek, user: paciorek.c}
- {name: Konrad Paszkiewicz, user: paszkiewicz.konrad}
- {name: Marian Petre, user: petre.m}
- {name: Jon Pipitone, user: pipitone.j}
- {name: Mark Plumbley, user: plumbley.m}
- {name: Michael Rezny, user: rezny.m}
- {name: Ariel Rokem, user: rokem.a}
- {name: Jorden Schossau, user: schossau.j}
- {name: Rachel Schutt, user: schutt.r}
- {name: Anthony Scopatz, user: scopatz.a}
- {name: Jeffrey Shelton, user: shelton.j}
- {name: Andrew Su, user: su.a}
- {name: Tracy Teal, user: teal.t}
- {name: Luke Tweddle, user: tweddle.l}
- {name: Todd Vision, user: vision.t}
- {name: Andrew Walker, user: walker.a}
- {name: Ben Waugh, user: waugh.b}
- {name: Ethan White, user: white.e}
- {name: Greg Wilson, user: wilson.g}
- {name: Paul Wilson, user: wilson.p}
- {name: Robin Wilson, user: wilson.r}
- {name: David Wolever, user: wolever.d}
