- https://github.com/r-gaia-cs/2014-05-12-furg
- https://github.com/wltrimbl/2014-05-12-cshl
- https://github.com/swcarpentry/2014-05-12-oicr-toronto
- https://github.com/jennybc/2014-05-12-ubc
- https://github.com/gvwilson/2014-05-19-scilifelab
- https://github.com/geocarpentry/2014-05-23-csdms
- https://github.com/badger-d/2014-06-02-monash
- https://github.com/apawlik/2014-06-03-cern
- https://github.com/gdevenyi/2014-06-04-cornell
- https://github.com/luispedro/2014-06-10-cyi
- https://github.com/luispedro/2014-06-15-khbp
- https://github.com/BernhardKonrad/2014-06-16-davis
- https://github.com/ptone/2014-06-16-claremont
- https://github.com/swcarpentry/2014-06-16-toronto
- https://github.com/cliburn/2014-06-16-duke
- https://github.com/swcarpentry/2014-06-24-wise-penn
- https://github.com/swcarpentry/2014-06-24-wise-toronto
- https://github.com/guyrt/2014-07-08-stonybrook
- https://github.com/swcarpentry/2014-07-15-toronto
- https://github.com/philippbayer/2014-07-30-pyconaus
- https://github.com/vu-bc/2014-08-12-vu
- https://github.com/mollygibson/2014-08-11-wustl
