- https://github.com/gvwilson/2014-01-20-montreal
- https://github.com/geocarpentry/2014-01-21-erdc
- https://github.com/arokem/2014-01-27-Stanford
- https://github.com/jennybc/2014-01-27-miami
- https://github.com/uiuc-cse/2014-01-30-cse
- https://github.com/geocarpentry/2014-01-30-mit
- https://github.com/swcarpentry/2014-01-31-ucsb
- https://github.com/apawlik/2014-02-03-TGAC
- https://github.com/damienirving/2014-02-10-hobart
- https://github.com/swcarpentry/2014-02-11-toronto
- https://github.com/bernhardkonrad/2014-02-22-SFU
- https://github.com/swcarpentry/2014-02-15-umkc
- https://github.com/nicercode/2014-02-13-UNSW
- https://github.com/nicercode/2014-02-18-UTS
- https://github.com/swcarpentry/2014-02-18-aims
- https://github.com/apawlik/2014-02-18-UCL
- https://github.com/justincely/2014-02-24-esac
- https://github.com/swcarpentry/2014-02-28-ethz
- https://github.com/swcarpentry/2014-03-17-nyu
- https://github.com/swcarpentry/2014-03-17-ucb
- https://github.com/swcarpentry/2014-03-17-uw
- https://github.com/swcarpentry/2014-04-14-wise
- https://github.com/swcarpentry/2014-04-14-pycon
- https://github.com/swcarpentry/2014-04-14-pycon-ngs
- https://github.com/swcarpentry/2014-04-14-pycon-r
