- https://github.com/swcarpentry/2011-11-07-toronto
- https://github.com/swcarpentry/2012-01-18-stsci
- https://github.com/swcarpentry/2012-02-20-itcp
- https://github.com/swcarpentry/2012-02-23-toronto
- https://github.com/swcarpentry/2012-03-07-indiana
- https://github.com/swcarpentry/2012-03-26-mbari
- https://github.com/swcarpentry/2012-03-28-nersc
- https://github.com/swcarpentry/2012-04-02-chicago
- https://github.com/swcarpentry/2012-04-14-utahstate
- https://github.com/swcarpentry/2012-04-30-ucl
- https://github.com/swcarpentry/2012-05-07-michiganstate
- https://github.com/swcarpentry/2012-05-14-newcastle
- https://github.com/swcarpentry/2012-05-16-alberta
- https://github.com/swcarpentry/2012-05-22-ubc
- https://github.com/swcarpentry/2012-06-18-jhu
- https://github.com/swcarpentry/2012-06-28-inria
- https://github.com/swcarpentry/2012-07-09-mit
- https://github.com/swcarpentry/2012-07-12-waterloo
- https://github.com/swcarpentry/2012-07-16-halifax
- https://github.com/swcarpentry/2012-07-19-utsc
- https://github.com/swcarpentry/2012-09-13-dafx
- https://github.com/swcarpentry/2012-09-17-oslo
- https://github.com/swcarpentry/2012-09-28-columbia
- https://github.com/swcarpentry/2012-10-08-purdue
- https://github.com/swcarpentry/2012-10-17-lbl
- https://github.com/swcarpentry/2012-10-18-ubc
- https://github.com/swcarpentry/2012-10-20-ucb
- https://github.com/swcarpentry/2012-10-22-newcastle
- https://github.com/swcarpentry/2012-10-23-caltech
- https://github.com/swcarpentry/2012-10-25-gmu
- https://github.com/swcarpentry/2012-10-30-oxford
- https://github.com/swcarpentry/2012-11-08-mcmaster
- https://github.com/swcarpentry/2012-11-10-wustl
- https://github.com/swcarpentry/2012-11-15-scripps
- https://github.com/swcarpentry/2012-11-28-unc
- https://github.com/swcarpentry/2012-11-30-hawaii
- https://github.com/swcarpentry/2012-12-04-edinburgh
- https://github.com/swcarpentry/2012-12-10-uta
- https://github.com/swcarpentry/2013-01-11-ubc
- https://github.com/swcarpentry/2013-01-12-chicago
- https://github.com/swcarpentry/2013-01-12-mcgill
- https://github.com/swcarpentry/2013-01-12-waterloo
- https://github.com/swcarpentry/2013-01-21-ubc
- https://github.com/swcarpentry/2013-01-22-tum
- https://github.com/swcarpentry/2013-01-24-camh
- https://github.com/swcarpentry/2013-01-25-tuebingen
- https://github.com/swcarpentry/2013-01-30-columbia
- https://github.com/swcarpentry/2013-01-31-vt
- https://github.com/swcarpentry/2013-02-05-ubc
- https://github.com/swcarpentry/2013-02-07-macquarie
- https://github.com/swcarpentry/2013-02-14-amos
- https://github.com/swcarpentry/2013-02-25-uwash
- https://github.com/swcarpentry/2013-03-04-lbl
- https://github.com/swcarpentry/2013-03-07-virginia
- https://github.com/swcarpentry/2013-03-20-aub
- https://github.com/swcarpentry/2013-03-23-utahstate
- https://github.com/swcarpentry/2013-03-24-kaust
- https://github.com/swcarpentry/2013-04-04-arizona
- https://github.com/swcarpentry/2013-04-04-ucl
- https://github.com/swcarpentry/2013-04-08-stellenbosch
- https://github.com/swcarpentry/2013-04-11-egi
- https://github.com/swcarpentry/2013-04-13-ucb
- https://github.com/swcarpentry/2013-04-18-manchester
- https://github.com/swcarpentry/2013-04-20-paris
- https://github.com/swcarpentry/2013-04-27-umaryland
- https://github.com/swcarpentry/2013-04-29-wisc
- https://github.com/swcarpentry/2013-05-02-vu
- https://github.com/swcarpentry/2013-05-06-geomar
- https://github.com/swcarpentry/2013-05-06-hhmi
- https://github.com/swcarpentry/2013-05-06-stanford
- https://github.com/swcarpentry/2013-05-09-lbl
- https://github.com/swcarpentry/2013-05-09-mozilla
- https://github.com/swcarpentry/2013-05-09-oxford
- https://github.com/swcarpentry/2013-05-13-ucdavis
- https://github.com/swcarpentry/2013-05-16-nescent
- https://github.com/swcarpentry/2013-05-18-krakow
- https://github.com/swcarpentry/2013-05-20-duke
- https://github.com/swcarpentry/2013-05-23-ucar
- https://github.com/swcarpentry/2013-05-23-umass
- https://github.com/swcarpentry/2013-05-30-alberta
- https://github.com/swcarpentry/2013-06-03-southampton
- https://github.com/swcarpentry/2013-06-03-tufts
- https://github.com/swcarpentry/2013-06-04-dssg
- https://github.com/swcarpentry/2013-06-06-sfu
- https://github.com/swcarpentry/2013-06-10-salk
- https://github.com/swcarpentry/2013-06-17-chicago
- https://github.com/swcarpentry/2013-06-24-wise
- https://github.com/swcarpentry/2013-06-25-scipy
- https://github.com/swcarpentry/2013-07-01-christchurch
- https://github.com/swcarpentry/2013-07-01-oklahoma
- https://github.com/swcarpentry/2013-07-03-oslo
- https://github.com/swcarpentry/2013-07-08-wuhan
- https://github.com/swcarpentry/2013-07-11-indiana
- https://github.com/swcarpentry/2013-07-15-bath
- https://github.com/swcarpentry/2013-07-15-vt
- https://github.com/swcarpentry/2013-07-16-cuahsi
- https://github.com/swcarpentry/2013-07-18-notredame
- https://github.com/swcarpentry/2013-07-18-washington
- https://github.com/swcarpentry/2013-07-27-cmu
- https://github.com/swcarpentry/2013-08-04-esa
- https://github.com/swcarpentry/2013-08-22-ku
- https://github.com/swcarpentry/2013-08-27-erdc
- https://github.com/swcarpentry/2013-08-28-wisc
- https://github.com/swcarpentry/2013-09-05-iowa
- https://github.com/swcarpentry/2013-09-12-bristol
- https://github.com/swcarpentry/2013-09-21-uwaterloo
- https://github.com/swcarpentry/2013-09-23-msu
- https://github.com/swcarpentry/2013-09-24-acpfgA
- https://github.com/swcarpentry/2013-09-26-ubc
- https://github.com/swcarpentry/2013-10-01-acpfgM
- https://github.com/swcarpentry/2013-10-29-vertpaleo
- https://github.com/swcarpentry/2013-11-14-whoi
- https://github.com/swcarpentry/2013-08-23-harvard
- https://github.com/swcarpentry/2013-09-16-stsci
- https://github.com/jdblischak/2013-09-19-chicago
- https://github.com/arokem/2013-09-16-ISI
- https://github.com/jdblischak/2013-10-03-pasteur
- https://github.com/swcarpentry/2013-10-09-canberra
- https://github.com/jdblischak/2013-10-17-uic
- https://github.com/swcarpentry/2013-10-24-greenwich
- https://github.com/justincely/2013-10-25-columbia
- https://github.com/chryswoods/2013-11-14-exeter
- https://github.com/damienirving/2013-11-25-unimelb
- https://github.com/mikej888/2013-12-03-edinburgh
- https://github.com/wltrimbl/2013-12-03-sesync
- https://github.com/bendmorris/2013-12-12-glasgow
- https://github.com/gvwilson/2013-12-16-dundee
- https://github.com/jooolia/2014-01-06-unb
- https://github.com/sje30/2014-01-07-cam
- https://github.com/adina/2014-01-08-iastate
- https://github.com/gvwilson/2014-01-13-toronto
- https://github.com/iglpdc/2014-01-13-uri
- https://github.com/uw-madison-aci/2014-01-13-wisc
- https://github.com/apawlik/2014-01-14-manchester
- https://github.com/swcarpentry/2014-01-18-ucb
- https://github.com/gvwilson/2014-01-20-montreal
- https://github.com/geocarpentry/2014-01-21-erdc
- https://github.com/arokem/2014-01-27-Stanford
- https://github.com/jennybc/2014-01-27-miami
- https://github.com/uiuc-cse/2014-01-30-cse
- https://github.com/geocarpentry/2014-01-30-mit
- https://github.com/swcarpentry/2014-01-31-ucsb
- https://github.com/apawlik/2014-02-03-TGAC
- https://github.com/damienirving/2014-02-10-hobart
- https://github.com/swcarpentry/2014-02-11-toronto
- https://github.com/bernhardkonrad/2014-02-22-SFU
- https://github.com/swcarpentry/2014-02-15-umkc
- https://github.com/karthik/2014-02-18-UTS
- https://github.com/karthik/2014-02-13-UNSW
- https://github.com/justincely/2014-02-24-esac
- https://github.com/swcarpentry/2014-03-17-nyu
- https://github.com/swcarpentry/2014-03-17-ucb
- https://github.com/swcarpentry/2014-03-17-uw
- https://github.com/swcarpentry/2014-04-14-wise
- https://github.com/swcarpentry/2014-04-14-pycon
- https://github.com/swcarpentry/2014-04-14-pycon-ngs
- https://github.com/swcarpentry/2014-04-14-pycon-r
