- https://github.com/mollygibson/2014-08-11-wustl
- https://github.com/vu-bc/2014-08-12-vu
- https://github.com/abostroem/2014-08-14-stanford
- https://github.com/r-gaia-cs/2014-08-18-ufrj
- https://github.com/resbaz/2014-08-18-unimelb
- https://github.com/rkiko/2014-08-21-kiel
- https://github.com/swcarpentry/2014-08-21-upenn
- https://github.com/wrightaprilm/2014-08-23-ttu
- https://github.com/UW-Madison-ACI/2014-08-25-wisc
- https://github.com/rbeagrie/2014-08-26-cam
- https://github.com/acviana/2014-08-28-ufrgs
- https://github.com/r-gaia-cs/2014-09-01-ccsl
- https://github.com/r-gaia-cs/2014-09-04-ccsl
- https://github.com/jrherr/2014-09-11-udel
- https://github.com/resbaz/2014-09-15-unimelb
- https://github.com/hpcarcher/2014-09-16-imperial
- https://github.com/jdblischak/2014-09-18-chicago
- http://github.com/karthik/2014-10-30-nw
