- https://github.com/DevasenaInupakutika/2014-07-10-Nottingham
- https://github.com/ivanov/2014-06-30-stanford
- https://github.com/dhavide/2014-07-02-smu
- https://github.com/cmacdonell/2014-07-10-epl
- https://github.com/erdavenport/2014-07-08-wise-toronto
- https://github.com/guyrt/2014-07-08-stonybrook
- https://github.com/jrherr/2014-07-10-esip
- https://github.com/dbarneche/2014-07-14-Dalhousie
- https://github.com/swcarpentry/2014-07-15-toronto
- https://github.com/swcarpentry/2014-07-17-aspb
- https://github.com/redcurry/2014-07-19-umich
- https://github.com/hpcarcher/2014-07-21-cranfield
- https://github.com/mckays630/2014-07-23-jfrc
- https://github.com/philippbayer/2014-07-30-pyconaus
- https://github.com/vu-bc/2014-08-12-vu
- https://github.com/mollygibson/2014-08-11-wustl
- https://github.com/resbaz/2014-08-18-unimelb
- https://github.com/rkiko/2014-08-21-kiel
- https://github.com/rbeagrie/2014-08-26-cam
- https://github.com/jrherr/2014-09-11-udel
- https://github.com/resbaz/2014-09-15-unimelb
- https://github.com/hpcarcher/2014-09-16-imperial
- https://github.com/r-gaia-cs/2014-08-18-ufrj
- https://github.com/UW-Madison-ACI/2014-08-25-wisc
- https://github.com/acviana/2014-08-28-ufrgs
- https://github.com/r-gaia-cs/2014-09-01-ccsl
- https://github.com/r-gaia-cs/2014-09-04-ccsl
