workshops:
- "au"
- "br"
- "ca"
- "ch"
- "cn"
- "cy"
- "de"
- "dk"
- "fr"
- "gb"
- "gh"
- "it"
- "jo"
- "kr"
- "lb"
- "nl"
- "no"
- "nz"
- "pl"
- "sa"
- "se"
- "th"
- "us"
- "za"
instructors:
- "au"
- "br"
- "ca"
- "cn"
- "de"
- "dk"
- "es"
- "fr"
- "gb"
- "ie"
- "il"
- "in"
- "it"
- "jp"
- "no"
- "nz"
- "pl"
- "se"
- "sg"
- "th"
- "us"
- "za"
