- https://github.com/aaren/2015-06-15-cambridge
- https://github.com/luispedro/2015-06-15-cfmehu
- https://github.com/iglpdc/2015-06-15-uconn
- https://github.com/mckays630/2015-06-17-ucstorrs
- https://github.com/lmwake/2015-06-18-StAndrews
- https://github.com/jrugis/2015-06-18-otago
# - https://github.com/dani-lbnl/2015-06-19-labvis
- https://github.com/mahdi-b/2015-06-21-UH-SWC
- https://github.com/guyrt/2015-06-21-s2i2
- https://github.com/jensv/2015-06-22-caltech
- https://github.com/erdavenport/2015-06-22-psu
- https://github.com/smcclatchy/2015-06-23-jackson
- https://github.com/sungeunbae/2015-06-23-massey
- https://github.com/apawlik/2015-06-24-dc-utrecht
- https://github.com/ashwinsrnth/2015-06-24-gatech
- https://github.com/uiuc-cse/2015-06-25-byu
- https://github.com/chendaniely/2015-06-25-jhu
- https://github.com/keszybz/2015-06-25-notre-dame
- https://github.com/suparee/2015-06-25-uw
- https://github.com/swcarpentry/2015-06-25-wise-toronto
- https://github.com/statkclee/2015-06-29-yonsei
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/jiffyclub/2015-07-06-scipy
- https://github.com/cmacdonell/2015-07-09-vpl
- https://github.com/damienirving/2015-07-13-amos
- https://github.com/harnesscloud/2015-07-15-feltham
- https://github.com/mlammens/2015-07-16-UCT
- https://github.com/tomwright01/2015-07-16-sickkids
- https://github.com/arohl/2015-07-20-perth
- https://github.com/fasrc/2015-07-22_SWC-R
- https://github.com/bio-swc-bne/2015-09-28-UQ
