- https://github.com/COMBINE-Australia/2015-04-08-SWC-UniMelb-Biosciences
- https://github.com/efran/2015-04-09-UW
- https://github.com/geocarpentry/2015-04-13-samsi
- https://github.com/ouinformatics/2015-04-15-ncar
- https://github.com/hpcarcher/2015-04-16-imperial
- https://github.com/alonzi/2015-04-16-uvalib
- https://github.com/jdblischak/2015-04-17-nw
- https://github.com/mqwilber/2015-04-17-ucsb
- https://github.com/rachelss/2015-04-18-ASU
- https://github.com/naupaka/2015-04-18-UT-Arlington
- https://github.com/eharstad/2015-04-22-UNO
- https://github.com/karawoo/2015-04-27-wsu
- https://github.com/statkclee/2015-04-29-pangyo
- https://github.com/ttimbers/2015-04-30-SFU
- https://github.com/resbaz/2015-05-04-matlab
- https://github.com/mckays630/2015-05-04-usfcms
- https://github.com/christinalk/2015-05-11-unm
- https://github.com/pbarmby/2015-05-11-westernu
- https://github.com/resbaz/2015-05-25-unimelb
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/jiffyclub/2015-07-06-scipy
- https://github.com/damienirving/2015-07-13-amos
