- https://github.com/resbaz/2015-06-29-qaeco-unimelb
- https://github.com/MonashBioinformaticsPlatform/15-07-swc-r
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/jiffyclub/2015-07-06-scipy
- https://github.com/dib-lab/2015-07-06-ucdavis
- https://github.com/marwahaha/2015-07-09-berkeley
- https://github.com/cmacdonell/2015-07-09-vpl
- https://github.com/damienirving/2015-07-13-amos
- https://github.com/resbaz/2015-07-13-unimelb
- https://github.com/harnesscloud/2015-07-15-feltham
- https://github.com/eharstad/2015-07-15-UNL
- https://github.com/mlammens/2015-07-16-UCT
- https://github.com/tomwright01/2015-07-16-sickkids
- https://github.com/arohl/2015-07-20-perth
- https://github.com/fasrc/2015-07-22_SWC-R
- https://github.com/billmills/2015-07-24-LSIUBC
- https://github.com/mperignon/2015-08-06-cuboulder
- https://github.com/andreww/2015-08-26-leeds
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/bio-swc-bne/2015-09-28-UQ
