- https://github.com/naupaka/2014-09-27-asu
- https://github.com/gvwilson/2014-09-29-iDigBio
- https://github.com/joryschossau/2014-09-30-msu
- https://github.com/iglpdc/2014-10-06-indiana
- https://github.com/mckays630/2014-10-06-osu
- https://github.com/swcarpentry/2014-10-06-rotman
- https://github.com/mattphotonman/2014-10-11-yale
- https://github.com/chwilk/2014-10-13-rice
- https://github.com/swcarpentry/2014-10-30-utoronto
- https://github.com/dbarneche/2014-10-31-USyd
- https://github.com/karthik/2014-10-31-nw
- https://github.com/dhaine/2014-11-06-fmv
- https://github.com/lgatto/2014-11-06-UZH
- https://github.com/anenadic/2014-11-10-manchester
- https://github.com/swcarpentry/2014-11-12-embl
- https://github.com/andreww/2014-11-24-leeds
- https://github.com/apawlik/2014-11-27-elixiruk-manchester
- https://github.com/jduckles/2014-11-27-uct
- https://github.com/hpcarcher/2014-12-03-edinburgh
- https://github.com/andreww/2015-01-14-leeds
