- https://github.com/marwahaha/2015-07-09-berkeley
- https://github.com/cmacdonell/2015-07-09-vpl
- https://github.com/damienirving/2015-07-13-amos
- https://github.com/resbaz/2015-07-13-unimelb
- https://github.com/harnesscloud/2015-07-15-feltham
- https://github.com/eharstad/2015-07-15-UNL
- https://github.com/mlammens/2015-07-16-UCT
- https://github.com/tomwright01/2015-07-16-sickkids
- https://github.com/arohl/2015-07-20-perth
- https://github.com/fasrc/2015-07-22_SWC-R
- https://github.com/usnistgov/2015-07-23-nist
- https://github.com/i5k-kinbre-script-share/2015-07-23-stanford
- https://github.com/billmills/2015-07-24-LSIUBC
- https://github.com/mperignon/2015-08-06-cuboulder
- https://github.com/mestato/2015-08-10-UTKnoxville
- https://github.com/eddelbuettel/2015-08-21-nw
- https://github.com/vu-bc/2015-08-20-vanderbilt
- https://github.com/datacarpentry/2015-08-24-Sloan-Kettering
- https://github.com/dgasmith/2015-08-24-stanford
- https://github.com/andreww/2015-08-26-leeds
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/bio-swc-bne/2015-09-28-UQ
- https://github.com/luispedro/2015-11-04-embl
