- https://github.com/resbaz/2015-06-29-qaeco-unimelb
- https://github.com/MonashBioinformaticsPlatform/2015-07-02-monash
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/jiffyclub/2015-07-06-scipy
- https://github.com/dib-lab/2015-07-06-ucdavis
- https://github.com/marwahaha/2015-07-09-berkeley
- https://github.com/cmacdonell/2015-07-09-vpl
- https://github.com/damienirving/2015-07-13-amos
- https://github.com/resbaz/2015-07-13-unimelb
- https://github.com/harnesscloud/2015-07-15-feltham
- https://github.com/eharstad/2015-07-15-UNL
- https://github.com/mlammens/2015-07-16-UCT
- https://github.com/tomwright01/2015-07-16-sickkids
- https://github.com/arohl/2015-07-20-perth
- https://github.com/fasrc/2015-07-22_SWC-R
- https://github.com/i5k-kinbre-script-share/2015-07-23-stanford
- https://github.com/billmills/2015-07-24-LSIUBC
- https://github.com/mperignon/2015-08-06-cuboulder
- https://github.com/mestato/2015-08-10-UTKnoxville
- https://github.com/eddelbuettel/2015-08-21-nw
- https://github.com/dgasmith/2015-08-24-stanford
- https://github.com/andreww/2015-08-26-leeds
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/bio-swc-bne/2015-09-28-UQ
- https://github.com/usnistgov/2015-07-23-nist
- https://github.com/dib-lab/2015-07-06-ucdavis
- https://github.com/uiuc-cse/2015-06-25-byu
- https://github.com/dani-lbnl/2015-06-19-labvis
- https://github.com/swcarpentry/2015-06-16-ttt-aciref
- https://github.com/swcarpentry/2015-06-12-ttt-iplant
- https://github.com/datacarpentry/2015-04-23-stanford
- https://github.com/jainsley/2015-03-20-UNL
- https://github.com/datacarpentry/2015-03-09-ISI-CODATA
- https://github.com/datacarpentry/2015-02-09-ucdavis
