- https://github.com/andreww/2014-11-24-leeds
- https://github.com/apawlik/2014-11-27-elixiruk-manchester
- https://github.com/jduckles/2014-11-27-uct
- https://github.com/hpcarcher/2014-12-03-edinburgh
- https://github.com/apawlik/2014-12-06-wise-krakow
- https://github.com/resbaz/2014-12-08-combine-r
- https://github.com/SWC-OSG-Workshop/2014-12-15-UChicago
- https://github.com/dhavide/2014-12-18-yale
- https://github.com/abostroem/2015-01-03-aas
- https://github.com/ianamunoz/2015-01-08-NIH
- https://github.com/Koltrane/2015-01-08-nber
- https://github.com/dbarneche/2014-12-11-ufsc
- https://github.com/supa-uk/2014-12-11-ugsupa
- https://github.com/andreww/2015-01-14-leeds
- https://github.com/jpallen/2015-01-14-oxford
- https://github.com/sophieclayton/2015-01-15-uw
- https://github.com/tomwright01/2015-01-29-sickkids
- https://github.com/resbaz/2015-02-16-resbaz-matlab
- https://github.com/resbaz/2015-02-16-resbaz-r
- https://github.com/resbaz/2015-02-16-resbaz-python
- https://github.com/damienirving/2015-07-13-amos
