- https://github.com/abostroem/2015-01-03-aas
- https://github.com/christinalk/2015-01-05-wise-cuboulder
- https://github.com/danabauer/2015-01-05-wise-umich
- https://github.com/geocarpentry/2015-01-07-instaar
- https://github.com/mckays630/2014-01-08-unl
- https://github.com/ianamunoz/2015-01-08-NIH
- https://github.com/Koltrane/2015-01-08-nber
- https://github.com/dhavide/2015-01-08-uoit
- https://github.com/igor-kozlov/2015-01-10-mcgill
- https://github.com/naupaka/2015-01-10-st_josephs
- https://github.com/jlant/2015-01-11-earlham
- https://github.com/philipwfowler/2015-01-13-oxford
- https://github.com/andreww/2015-01-14-leeds
- https://github.com/jpallen/2015-01-14-oxford
- https://github.com/sesync-ci/2015-01-15-umd
- https://github.com/sophieclayton/2015-01-15-uw
- https://github.com/naupaka/2015-01-26-tulane
- https://github.com/tomwright01/2015-01-29-sickkids
- https://github.com/uiuc-cse/2015-01-29-uiuc
- https://github.com/apawlik/2015-02-03-CDT-reg-medicine
- https://github.com/resbaz/2015-02-16-resbaz-matlab
- https://github.com/resbaz/2015-02-16-resbaz-python
- https://github.com/resbaz/2015-02-16-resbaz-r
- https://github.com/naupaka/2015-02-21-iplant
- https://github.com/damienirving/2015-07-13-amos
