- https://github.com/anelda/2015-09-06-saeon
- https://github.com/ashwinsrnth/2015-09-07-clemson
- https://github.com/dpshelio/2015-09-07-guildford
- https://github.com/callaghanmt/2015-09-10-leeds
- https://github.com/rgaiacs/2015-09-10-usp
- https://github.com/jdblischak/2015-09-15-chicago
- https://github.com/emilydolson/2015-09-15-msu
- https://github.com/Southampton-RSG/2015-09-17-southampton
- https://github.com/bio-swc-bne/2015-09-28-UQ
- https://github.com/monashbioinformaticsplatform/2015-09-28-rbioinformatics
- https://github.com/jcu-eresearch/2015-10-01-JamesCookUni
- https://github.com/luispedro/2015-11-04-embl
- https://github.com/UMSWC/2015-10-19-UMich
