- https://github.com/karawoo/2015-04-27-wsu
- https://github.com/statkclee/2015-04-29-pangyo
- https://github.com/ttimbers/2015-04-30-SFU
- https://github.com/resbaz/2015-05-04-matlab
- https://github.com/swcarpentry/2015-05-04-lbl
- https://github.com/drarnakarick/2015-05-04-swinpython
- https://github.com/mckays630/2015-05-04-usfcms
- https://github.com/christinalk/2015-05-11-unm
- https://github.com/pbarmby/2015-05-11-westernu
- https://github.com/chendaniely/2015-05-12-BUSM
- https://github.com/lgatto/2015-05-14-Stellenbosch
- https://github.com/oulibraries/2015-05-19-ou
- https://github.com/resbaz/2015-05-25-unimelb
- https://github.com/ouinformatics/2015-05-27-osu
- https://github.com/aaren/2015-06-15-cambridge
- https://github.com/luispedro/2015-06-15-cfmehu
- https://github.com/jensv/2015-06-22-caltech
- https://github.com/bio-swc-bne/2015-07-02-UQ
- https://github.com/jiffyclub/2015-07-06-scipy
- https://github.com/damienirving/2015-07-13-amos
- https://github.com/harnesscloud/2015-07-15-feltham
- https://github.com/mlammens/2015-07-16-UCT
- https://github.com/arohl/2015-07-20-perth
